name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: devel
      run: sudo apt-get update -y && sudo apt-get install -y libcurl4-gnutls-dev
      
    - name: make
      run: make all
      
